kylemanna/docker-bitcoind

- Dockerfile
- README.md
It's always useful to be able to check the output, so I added `-printconsole` to the default arguments, and updated the documentation to show how to use `docker logs`
> Make ouput available by default

- bin/btc_bootstrap
- docs/torrent_bootstrap.md
If the bootstrap file already exists, verify its check-sum and re-download only if necessary.
See http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption-V
Resolves #5
Tested on my VPS
> Avoiding downloading the bootstrap file when it's not necessary

- docs/torrent_bootstrap.md
Change the placeholder for "kylemanna/bitcoind" to match other docs in this same repository, and put it at the right position
> Fix example btc_bootstrap invocation in doc

- bin/btc_oneshot
The `rpcallowip ` option in bitcoin core 0.10.0 no longer supports string wildcard matching. Currently when running this docker-bitcoind container, I get the following error:
```
bitcoind error: Error: Invalid -rpcallowip subnet specification: *. Valid are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).
```
This commit updates the rpcallowip option for bitcoin core 0.10.0.
Here are the bitcoin core release notes referencing the change:
https://github.com/bitcoin/bitcoin/blob/ce56f5621a94dcc2159ebe57e43da727eab18e6c/doc/release-notes/release-notes-0.10.0.md#rpc-access-control-changes
> Update rpcallowip argument for bitcoin core 0.10.0

- bin/btc_init
I needed to be able to set the password while starting the container for the first time from env variables. Useful with docker-compose. Please consider merging.
> added env-configurable bitcoin.conf variables

- .travis.yml
This adds a basic travis-ci testing support for this repository. It is based on a code from official docker images, like https://github.com/docker-library/memcached and https://github.com/docker-library/mysql.
> travis-ci support

- CONTRIBUTING.md
The link to Travis-CI is wrong - fixed.
> [doc]: fixed wrong link in documentation

- bin/btc_init
This one is ugly: It causes the generated password to be a default one of
`dd if=/dev/urandom bs=33 count=1 status=none | base64`
instead of a random one.
Testcase:
```
$ docker run --name=bitcoind-node -d kylemanna/bitcoind
$ docker exec -it bitcoind-node /bin/bash -c "cat /bitcoin/.bitcoin/bitcoin.conf"
```
Result:
```
[...]
rpcuser=bitcoinrpc
rpcpassword=dd if=/dev/urandom bs=33 count=1 status=none | base64
$
```
Expected result: A random string...
This is caused by the substitution not being evaluated, e.g.:
```
ubuntu@test:~$ echo "rpcpassword = ${RPCPASSWORD:-dd if=/dev/urandom bs=33 count=1 status=none | base64}"
rpcpassword = dd if=/dev/urandom bs=33 count=1 status=none | base64
```
What you want instead is
```
ubuntu@test:~$ echo "rpcpassword = ${RPCPASSWORD:-`dd if=/dev/urandom …
```
> [critical]: fix password generation

- Dockerfile
Previously, basically anyone in the position to MITM the network connection of the build server for this image could have easily compromised it!
@kylemanna Seems you like to live dangerously?
Ref: https://www.phoronix.com/scan.php?page=news_item&px=Short-PGP-Collision-Attacks
> Enforce the full OpenPGP fingerprint of ppa:bitcoin/bitcoin

- Dockerfile
- bin/btc_oneshot
- docker-entrypoint.sh
* Update to use upstream packaged binary distribution instead of Ubuntu PPA which has been abandoned.
* Clean things up slightly.
* Fix RPC bug.
* Improve script compatibility with standard POSIX compliant shells.
* Closes #62 and #66
> Update to use upstream bitcoind v0.20.1

- bin/btc_oneshot
Previously it only bound to IPv4 address but had ACLs only allowing
IPv6 addresses. Fix this by binding to all and allowing both.
Closes #64
> oneshot: rpc: Fix IPv4 and IPv6 binding and ACL

- bin/btc_oneshot
* IPv6 support is too flakey and hit and miss in Docker. Drop it outright.
* Bind to IPv4 address only and be done. Leave comment for future poor
soul trying to work with IPv6 and Docker.
> oneshot: rpc: Drop IPv6 support

- CONTRIBUTING.md
Hi! I noticed that the page referenced in CONTRIBUTING.md has moved with the following message when you hit the page:
`This file has moved to process/submitting-patches.rst`
So I updated the URL accordingly.
> fix: broken URL to SubmittingPatches page on kernel.org

- README.md
- docs/config.md
Documentation now shows example configurations using /bitcoin/.bitcoin (instead of /bitcoin) volume mount point
> Volume declaration changes reflected in documentation (fixes issue #74)

- Dockerfile
Needs some quick testing. This enables taproot.
> release: Bump to v0.21.1

- Dockerfile
* Update signing key and verification method as the hashes are now
signed with many keys and fetching _all_ of them seems overkill.
Closes #90
> release: Bump to v22.0

- bin/btc_init
- docs/config.md
Hi There,
Please find attached PR to add a `REGTEST` environment variable to configure regtest mode for easier local development.
We have found it much simpler to configure a development config using docker compose without needing to maintain an extra `bitcoin.conf` file for changing core functions of bitcoind.
Please let me know what you think
> Add Regtest parameter

- .travis.yml
- Dockerfile
This pull requests adds multiarch setup to the Dockerfile. The image is built for amd64, arm64 and riscv64.
In order to build it locally you might have to setup a multiarch environment:
``` bash 
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
$ docker buildx create --name multiarch --driver docker-container --use
$ docker buildx inspect --bootstrap
```
> Build image for amd64, arm64 and riscv64 (Issue #85)

- Dockerfile
* Fix bugs introduced by #103
* Add missing dependency for `libatomic1` which is need at least by `riscv64`
Build command:
docker buildx build --platform linux/arm64,linux/amd64,linux/riscv64 --pull .
image=test
docker buildx build --platform linux/amd64 -t $image --load .
docker run --rm -it $image --version
> dockerfile: Fix multi-platform builds

- Dockerfile
Tested and working perfectly in https://github.com/sethforprivacy/docker-bitcoind/commit/26f102a3d13124f2da6ea0f139a3964f6feb53f5 on multiple servers.
> Bump to v26.1

- Dockerfile
Ubuntu 23.04+ introduced a change that creates a default `ubuntu` user with the UID/GID we use for the `bitcoin` user.
In order to not break current permissions this simply deletes the default user and creates the `bitcoin` user as we always have.
> Fix Ubuntu 24.04 base image builds

- Dockerfile
Tested and running locally with no issues.
> Bitcoin Core 28.0

- Dockerfile
https://bitcoincore.org/en/releases/29.0/
> Bump Bitcoin Core to v29.0
